# Solution 1

In [7]:
import numpy as np 

a  = np.array([1, 2, 3, 4, 5, 6])
b = np.array([6, 5, 4, 3, 2, 1])

print(a > b)
print(a >= b)
print(a < b)
print(a <= b)

[False False False  True  True  True]
[False False False  True  True  True]
[ True  True  True False False False]
[ True  True  True False False False]


# Solution 2

In [9]:
import numpy as np 
a = np.zeros(10)
print(a)

b = np.ones(10)
print(b)

c = np.full(10, 5)
print(c)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


# Solution 3


In [7]:
import numpy as np 

a = np.array([[5, 3, 3, 7], [2, 4, 6, 5]])

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

35
[ 7  7  9 12]
[18 17]


# Solution 4

In [13]:
import numpy as np

a = np.array([[4,5,7,8], [7,5,3,1]])
b = np.array([[5,3,7,8], [6,8,2,4]])

c = np.add(a, b)
print(c)
d = np.subtract(a, b)
print(d)
e = np.multiply(a, b)
print(e)
f = np.divide(a, b)
print(f)

[[ 9  8 14 16]
 [13 13  5  5]]
[[-1  2  0  0]
 [ 1 -3  1 -3]]
[[20 15 49 64]
 [42 40  6  4]]
[[0.8        1.66666667 1.         1.        ]
 [1.16666667 0.625      1.5        0.25      ]]


# Solution 5

In [16]:
a = np.array([45, 90, 180])

sinus = np.sin(a)
print(sinus)

cos = np.cos(a)
print(cos)

tan = np.tan(a)
print(tan)

[ 0.85090352  0.89399666 -0.80115264]
[ 0.52532199 -0.44807362 -0.59846007]
[ 1.61977519 -1.99520041  1.33869021]


# Solution 6

In [10]:
import pandas as pd 

d = {"name": ["Messi", "Ronaldo", "Neymar", "Mbappe", "Halaad"], "age":[33, 35, 28, 21, 19], "score": [9.5, 9, 8.8, 8.5, 8]}

df = pd.DataFrame(d)

print(df)

      name  age  score
0    Messi   33    9.5
1  Ronaldo   35    9.0
2   Neymar   28    8.8
3   Mbappe   21    8.5
4   Halaad   19    8.0


# Solution 7

In [17]:
import pandas as pd 
d = {"name": ["Messi", "Ronaldo", "Neymar", "Mbappe", "Halaad"], "age":[33, 35, 28, 21, 19], "score": [9.5, 9, 8.8, 8.5, 8]}
dd = pd.DataFrame(d, columns=["name", "score"])
print(dd)

      name  score
0    Messi    9.5
1  Ronaldo    9.0
2   Neymar    8.8
3   Mbappe    8.5
4   Halaad    8.0


# Solution 8

In [20]:
import pandas as pd 
d = {"name": ["Messi", "Ronaldo", "Neymar", "Mbappe", "Halaad"], "age":[33, 35, 28, 21, 19], "score": [9.5, 9, 8.8, 8.5, 8]}
a = {"name": ["Rashford", "Ansu Fati", "Bruno Frenades", "Kevin Debruyn", "Salah"], "age":[22, 18, 22, 28, 26], "score": [8, 8, 8.8, 9, 8]}

df = pd.DataFrame(d)
dd = pd.DataFrame(a)

print(pd.concat([df, dd]))

             name  age  score
0           Messi   33    9.5
1         Ronaldo   35    9.0
2          Neymar   28    8.8
3          Mbappe   21    8.5
4          Halaad   19    8.0
0        Rashford   22    8.0
1       Ansu Fati   18    8.0
2  Bruno Frenades   22    8.8
3   Kevin Debruyn   28    9.0
4           Salah   26    8.0


# Solution 9

In [26]:
import pandas as pd 
import numpy as np 
d = {"name": ["Messi", "Ronaldo", "Neymar", "Mbappe", "Halaad"], "age":[33, 35, 28, np.nan, 21], "score": [9.5, 9, np.nan, 8, np.nan]}
df = pd.DataFrame(d)
print(df.isnull())

    name    age  score
0  False  False  False
1  False  False  False
2  False  False   True
3  False   True  False
4  False  False   True


# Solution 10


In [32]:
import pandas as pd 
color = {"color": ['red', 'green', 'blue',"yellow"]}

dd = pd.DataFrame(color)

print(dd.to_string(index=False))

  color
    red
  green
   blue
 yellow
